import type { BlogPost } from '@/types'

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    slug: 'industrie-4-0-revolution-production',
    title: 'Industrie 4.0 : La révolution silencieuse de la production mondiale',
    excerpt: 'Comment les technologies de l\'Industrie 4.0 transforment radicalement les usines du monde entier et créent de nouveaux avantages compétitifs.',
    content: `L'Industrie 4.0 représente bien plus qu'une évolution technologique : c'est une transformation fondamentale de la façon dont nous produisons, gérons et optimisons les processus industriels...`,
    category: 'Industrie 4.0',
    author: 'Thomas Nguyen',
    date: '2024-11-15',
    readTime: 8,
    imageUrl: 'https://images.unsplash.com/photo-1567789884554-0b844b597180?w=800&q=80',
    tags: ['Industrie 4.0', 'Automatisation', 'Innovation', 'Production'],
  },
  {
    id: '2',
    slug: 'ia-maintenance-predictive-guide-complet',
    title: 'IA et Maintenance Prédictive : Le guide complet pour les industriels',
    excerpt: 'Découvrez comment l\'intelligence artificielle révolutionne la maintenance industrielle et comment l\'implémenter dans votre entreprise.',
    content: `La maintenance prédictive basée sur l'IA permet aux industriels de passer d'une approche réactive à une approche proactive...`,
    category: 'IA',
    author: 'Sarah Diallo',
    date: '2024-11-08',
    readTime: 12,
    imageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80',
    tags: ['IA', 'Maintenance Prédictive', 'Machine Learning', 'IoT'],
  },
  {
    id: '3',
    slug: 'iot-industriel-iiot-architecture',
    title: 'Architecture IIoT : Construire une infrastructure robuste pour l\'industrie',
    excerpt: 'Les bonnes pratiques pour concevoir et déployer une architecture IoT industrielle fiable, sécurisée et scalable.',
    content: `L'Internet des Objets Industriel (IIoT) pose des défis architecturaux spécifiques que les approches IoT grand public ne permettent pas de résoudre...`,
    category: 'IoT',
    author: 'Marc Lebrun',
    date: '2024-10-28',
    readTime: 10,
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80',
    tags: ['IoT', 'IIoT', 'Architecture', 'Edge Computing'],
  },
  {
    id: '4',
    slug: 'transformation-digitale-pme-industrielles',
    title: 'Comment les PME industrielles réussissent leur transformation digitale',
    excerpt: 'Étude de cas et méthodologie pour les PME qui souhaitent se digitaliser sans se noyer dans la complexité.',
    content: `La transformation digitale n'est pas l'apanage des grands groupes. Les PME industrielles ont tout à gagner à entamer ce voyage, à condition de bien s'y préparer...`,
    category: 'Transformation Digitale',
    author: 'Isabelle Fontaine',
    date: '2024-10-15',
    readTime: 7,
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    tags: ['PME', 'Transformation Digitale', 'Stratégie', 'Digital'],
  },
  {
    id: '5',
    slug: 'data-driven-manufacturing-kpis',
    title: 'Les 15 KPIs essentiels pour piloter votre usine par les données',
    excerpt: 'Quels indicateurs suivre pour optimiser votre performance industrielle ? Notre guide des métriques incontournables.',
    content: `Le pilotage par les données commence par le choix des bons indicateurs. Trop d'entreprises se noient dans les données sans savoir quoi mesurer...`,
    category: 'Data',
    author: 'Thomas Nguyen',
    date: '2024-10-02',
    readTime: 9,
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    tags: ['Data Analytics', 'KPIs', 'Manufacturing', 'Performance'],
  },
  {
    id: '6',
    slug: 'cybersecurite-ot-it-convergence',
    title: 'Cybersécurité OT/IT : Les enjeux de la convergence pour l\'industrie',
    excerpt: 'Avec la digitalisation, les risques cyber s\'étendent aux systèmes opérationnels. Comment protéger vos actifs industriels ?',
    content: `La convergence IT/OT ouvre de nouvelles opportunités, mais aussi de nouvelles surfaces d'attaque. La cybersécurité industrielle devient un impératif stratégique...`,
    category: 'Industrie 4.0',
    author: 'Marc Lebrun',
    date: '2024-09-18',
    readTime: 11,
    imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&q=80',
    tags: ['Cybersécurité', 'OT', 'IT', 'Sécurité Industrielle'],
  },
  {
    id: '7',
    slug: 'machine-learning-controle-qualite',
    title: 'Vision par ordinateur et contrôle qualité : Zéro défaut à grande échelle',
    excerpt: 'La vision artificielle permet d\'atteindre des taux de détection des défauts proches de 100%. Retour d\'expérience et bonnes pratiques.',
    content: `Le contrôle qualité visuel automatisé par IA représente l'une des applications les plus matures et les plus rentables de l'intelligence artificielle en industrie...`,
    category: 'IA',
    author: 'Sarah Diallo',
    date: '2024-09-05',
    readTime: 8,
    imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80',
    tags: ['Vision Artificielle', 'Contrôle Qualité', 'Deep Learning', 'Automatisation'],
  },
  {
    id: '8',
    slug: 'cloud-industrie-hybride-edge',
    title: 'Cloud hybride et Edge Computing : La combinaison gagnante pour l\'industrie',
    excerpt: 'Pourquoi l\'industrie ne doit pas choisir entre cloud et edge, mais combiner intelligemment les deux approches.',
    content: `Le débat cloud vs edge est dépassé. L'industrie moderne a besoin d'architectures hybrides qui tirent le meilleur des deux mondes...`,
    category: 'IoT',
    author: 'Isabelle Fontaine',
    date: '2024-08-22',
    readTime: 9,
    imageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&q=80',
    tags: ['Cloud', 'Edge Computing', 'Architecture', 'Industrie'],
  },
  {
    id: '9',
    slug: 'supply-chain-resilience-technologie',
    title: 'Résilience de la supply chain : Comment la technologie réduit les risques',
    excerpt: 'Les crises récentes ont mis à nu la fragilité des chaînes d\'approvisionnement. Les technologies digitales apportent de nouvelles solutions de résilience.',
    content: `La pandémie et les tensions géopolitiques ont révélé la vulnérabilité des supply chains mondiales. Comment la technologie permet-elle de construire des chaînes plus résilientes ?...`,
    category: 'Transformation Digitale',
    author: 'Marc Lebrun',
    date: '2024-08-08',
    readTime: 10,
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80',
    tags: ['Supply Chain', 'Résilience', 'Logistique', 'Digital'],
  },
  {
    id: '10',
    slug: 'energie-verte-industrie-optimisation',
    title: 'Industrie verte : L\'optimisation énergétique par les données',
    excerpt: 'Les industriels qui digitalisent leur gestion énergétique réduisent leurs coûts de 20 à 30% tout en atteignant leurs objectifs RSE.',
    content: `La transition énergétique n'est plus une contrainte pour l'industrie, mais une opportunité de compétitivité. Voici comment les données transforment la gestion de l'énergie...`,
    category: 'Data',
    author: 'Thomas Nguyen',
    date: '2024-07-25',
    readTime: 7,
    imageUrl: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&q=80',
    tags: ['Énergie', 'RSE', 'Data Analytics', 'Développement Durable'],
  },
]

export const blogCategories = ['Tous', 'Industrie 4.0', 'IA', 'IoT', 'Transformation Digitale', 'Data']