import type { JobOffer, Sector, Stat } from '@/types'

export const jobOffers: JobOffer[] = [
  {
    id: '1',
    title: 'Ingénieur Automatisme Senior',
    department: 'Ingénierie',
    location: 'Pointe-Noire, Congo',
    type: 'CDI',
    description: 'Nous recherchons un ingénieur automatisme expérimenté pour concevoir et déployer des solutions d\'automatisation complexes chez nos clients industriels.',
    requirements: [
      'Bac+5 en automatisme, électrotechnique ou génie industriel',
      '5+ ans d\'expérience en automatisme industriel',
      'Maîtrise des automates Siemens (S7-300/400/1500) et Schneider',
      'Expérience en SCADA (WinCC, Wonderware)',
      'Connaissance des protocoles industriels (OPC-UA, Profinet, Modbus)',
      'Anglais technique courant',
    ],
    benefits: [
      'Package salarial compétitif',
      'Véhicule de service',
      'Formation continue certifiante',
      'Participation aux bénéfices',
      'Mutuelle premium',
      'Projets internationaux',
    ],
  },
  {
    id: '2',
    title: 'Data Analyst / Data Engineer',
    department: 'Digital & Data',
    location: 'Brazzaville, Congo',
    type: 'CDI',
    description: 'Rejoignez notre équipe Data pour aider nos clients industriels à exploiter la puissance de leurs données et construire des solutions analytics avancées.',
    requirements: [
      'Bac+5 en informatique, statistiques ou data science',
      '3+ ans d\'expérience en data engineering ou analytics',
      'Maîtrise de Python, SQL et outils BI (Power BI, Tableau)',
      'Expérience avec les plateformes cloud (Azure, AWS)',
      'Connaissance des architectures data (Data Lake, Data Warehouse)',
      'Capacité à vulgariser les concepts techniques',
    ],
    benefits: [
      'Salaire attractif + primes',
      'Télétravail partiel',
      'Budget formation 5 000€/an',
      'Matériel dernière génération',
      'Environnement startup dans grand groupe',
    ],
  },
  {
    id: '3',
    title: 'Chef de Projet Digital',
    department: 'Project Management',
    location: 'Pointe-Noire, Congo',
    type: 'CDI',
    description: 'Pilotez des projets de transformation digitale complexes et multi-sites pour nos clients industriels grands comptes.',
    requirements: [
      'Bac+5 école d\'ingénieurs ou management',
      '5+ ans de gestion de projet IT/digital',
      'Certification PMP ou Prince2 appréciée',
      'Expérience en environnement industriel',
      'Leadership et capacité à gérer plusieurs projets en parallèle',
      'Bilinguisme français/anglais',
    ],
    benefits: [
      'Package complet et négociable',
      'Voiture de fonction',
      'Prime variable sur performance',
      'Voyages et projets internationaux',
      'Évolution rapide vers direction de BU',
    ],
  },
  {
    id: '4',
    title: 'Développeur Full Stack',
    department: 'Digital & Software',
    location: 'Pointe-Noire, Congo',
    type: 'CDI',
    description: 'Développez des applications web et mobiles innovantes pour nos solutions industrielles et plateformes IoT/Analytics.',
    requirements: [
      'Bac+3 à Bac+5 en informatique',
      '3+ ans de développement web full stack',
      'Maîtrise de React/Next.js et Node.js',
      'Expérience avec les API REST et GraphQL',
      'Connaissance des bases de données (PostgreSQL, MongoDB)',
      'Pratique DevOps (Docker, CI/CD)',
    ],
    benefits: [
      'Salaire selon profil et expérience',
      'Télétravail 3j/semaine',
      'Stack technologique moderne',
      'Mentoring par des seniors',
      'Participation aux conférences tech',
    ],
  },
]

export const sectors: Sector[] = [
  {
    id: '1',
    slug: 'industrie-manufacturiere',
    title: 'Industrie Manufacturière',
    description: 'L\'industrie manufacturière fait face à une révolution technologique sans précédent. NOISIM accompagne les fabricants dans leur transition vers l\'usine du futur.',
    challenges: [
      'Pression sur les coûts de production',
      'Exigences croissantes de qualité',
      'Pénurie de main-d\'œuvre qualifiée',
      'Complexité croissante des gammes produits',
      'Transition vers la production durable',
    ],
    solutions: [
      'Automatisation des lignes de production',
      'Contrôle qualité par vision artificielle',
      'Maintenance prédictive',
      'MES (Manufacturing Execution System)',
      'Traçabilité et conformité',
    ],
    benefits: [
      'Productivité augmentée de 30 à 50%',
      'Taux de défauts réduit de 90%+',
      'Flexibilité de production accrue',
      'Conformité réglementaire garantie',
    ],
    useCases: [
      'Usine automobile entièrement automatisée',
      'Contrôle qualité 100% par IA',
      'Jumeaux numériques d\'usine',
    ],
    icon: 'Factory',
  },
  {
    id: '2',
    slug: 'petrole-gaz',
    title: 'Pétrole & Gaz',
    description: 'Le secteur pétrolier et gazier exige fiabilité, sécurité et efficacité opérationnelle maximales. NOISIM apporte des solutions technologiques adaptées aux environnements les plus exigeants.',
    challenges: [
      'Sécurité des opérations en environnement dangereux',
      'Maintenance d\'actifs distants et critiques',
      'Optimisation de la production',
      'Conformité réglementaire stricte',
      'Transition énergétique',
    ],
    solutions: [
      'Systèmes de contrôle-commande (DCS/PLC)',
      'Surveillance d\'actifs en temps réel',
      'Maintenance prédictive avancée',
      'Gestion des alarmes',
      'Surveillance environnementale',
    ],
    benefits: [
      'Réduction des incidents de sécurité',
      'Optimisation du taux de production',
      'Réduction des coûts de maintenance',
      'Conformité incendi renforcée',
    ],
    useCases: [
      'SCADA de supervision de pipeline',
      'Maintenance prédictive de compresseurs',
      'Monitoring environnemental',
    ],
    icon: 'Droplets',
  },
  {
    id: '3',
    slug: 'energie',
    title: 'Énergie',
    description: 'La transition énergétique crée de nouveaux défis opérationnels. NOISIM aide les acteurs de l\'énergie à optimiser leurs actifs et à intégrer les nouvelles sources renouvelables.',
    challenges: [
      'Intégration des énergies renouvelables intermittentes',
      'Optimisation des réseaux de distribution',
      'Gestion de la demande et flexibilité',
      'Réduction des pertes réseau',
      'Cybersécurité des infrastructures critiques',
    ],
    solutions: [
      'SCADA de gestion de réseau',
      'Systèmes de gestion de l\'énergie (EMS)',
      'Analytics prédictive pour éolien/solaire',
      'Smart metering',
      'Stockage et gestion de batteries',
    ],
    benefits: [
      'Réduction des pertes réseau de 15%',
      'Meilleure intégration des ENR',
      'Optimisation des coûts d\'équilibrage',
      'Amélioration de la qualité de fourniture',
    ],
    useCases: [
      'Gestion de parc éolien offshore',
      'Smart grid distribution',
      'Optimisation hydroélectrique',
    ],
    icon: 'Zap',
  },
  {
    id: '4',
    slug: 'logistique',
    title: 'Logistique',
    description: 'La logistique est au cœur de la compétitivité. NOISIM déploie des solutions technologiques pour rendre vos opérations plus rapides, plus précises et plus rentables.',
    challenges: [
      'Complexité croissante des flux',
      'Exigences de livraison toujours plus strictes',
      'Gestion des retours (reverse logistics)',
      'Optimisation des coûts de transport',
      'Visibilité temps réel sur la supply chain',
    ],
    solutions: [
      'WMS (Warehouse Management System)',
      'TMS (Transport Management System)',
      'Automatisation d\'entrepôts',
      'RFID et traçabilité',
      'Optimisation des tournées',
    ],
    benefits: [
      'Taux de service > 98%',
      'Productivité d\'entrepôt +40%',
      'Réduction des coûts logistiques',
      'Traçabilité complète',
    ],
    useCases: [
      'Entrepôt e-commerce automatisé',
      'Optimisation flotte de livraison',
      'Cross-docking automatisé',
    ],
    icon: 'Truck',
  },
  {
    id: '5',
    slug: 'distribution',
    title: 'Distribution',
    description: 'Les distributeurs font face à l\'omnicanal et aux exigences de disponibilité immédiate. NOISIM les aide à digitaliser et optimiser leurs opérations.',
    challenges: [
      'Gestion omnicanale complexe',
      'Prévision de la demande difficile',
      'Ruptures de stock et surstocks',
      'Concurrence des pure players',
      'Marges sous pression',
    ],
    solutions: [
      'Prévision de la demande par IA',
      'Gestion des approvisionnements automatisée',
      'Optimisation des assortiments',
      'Click & Collect et gestion omnicanale',
      'Plateformes analytics commerciales',
    ],
    benefits: [
      'Réduction des ruptures de 60%',
      'Optimisation des stocks',
      'Amélioration des marges',
      'Meilleure expérience client',
    ],
    useCases: [
      'Prévision IA pour grande distribution',
      'Optimisation des stocks multi-sites',
      'Plateforme omnicanale',
    ],
    icon: 'ShoppingCart',
  },
  {
    id: '6',
    slug: 'telecommunications',
    title: 'Télécommunications',
    description: 'Les opérateurs télécom doivent se transformer pour faire face à l\'explosion des usages et à la concurrence. NOISIM accompagne leur transformation numérique.',
    challenges: [
      'Explosion des usages data',
      'Déploiement 5G et fibre',
      'Optimisation des réseaux',
      'Expérience client digitale',
      'Monétisation de nouveaux services',
    ],
    solutions: [
      'OSS/BSS modernisation',
      'Network Analytics',
      'Automatisation NOC/SOC',
      'Portails clients self-service',
      'Plateformes API Management',
    ],
    benefits: [
      'Réduction du OPEX réseau',
      'Amélioration du NPS',
      'Time-to-market accéléré',
      'Monétisation de la data',
    ],
    useCases: [
      'NOC automatisé par IA',
      'Portail client B2B',
      'Analytics réseau prédictive',
    ],
    icon: 'Radio',
  },
]

export const stats: Stat[] = [
  { value: 3, suffix: '+', label: 'Années d\'existance' },
  { value: 5, suffix: '+', label: 'Partenaires' },
  { value: 6, suffix: '+', label: 'Secteurs accompagnés' },
  { value: 100, suffix: '%', label: 'Satisfaction client' },
]